services:
  main:
    build: .
    container_name: main
    depends_on:
      - mysql
    ports:
      - 8007:8007
    environment:
      - YMIRBLOG_MYSQL_DATABASE=db
      - YMIRBLOG_MYSQL_USER=root
      - YMIRBLOG_MYSQL_PASSWORD=pw
      - YMIRBLOG_MYSQL_HOST=mysql
      - YMIRBLOG_MYSQL_PORT=3306
      - HTTP_PORT=8007
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    restart: always
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pw
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306